;; -*- mode: emacs-lisp; coding: emacs-mule; -*-
;; --------------------------------------------------------------------------
;; Desktop File for Emacs
;; --------------------------------------------------------------------------
;; Created Mon Apr 13 12:29:03 2015
;; Desktop file format version 206
;; Emacs version 24.4.51.2
(setq revive:frame-configuration-to-restore
  '(progn 
     (revive:restore-frame '((tool-bar-position . top) (explicit-name . t) (icon-name) (bottom-divider-width . 0) (right-divider-width . 0) (top . 100) (left . 100) (unsplittable) (modeline . t) (width . 80) (height . 35) (visibility . t) (cursor-color . "Red") (border-color . "#2a2a2a") (background-mode . light) (fringe) (fullscreen) (alpha) (scroll-bar-width . 0) (cursor-type . box) (auto-lower) (auto-raise) (icon-type) (title) (buffer-predicate) (tool-bar-lines . 1) (menu-bar-lines . 0) (right-fringe . 12) (left-fringe . 4) (line-spacing) (background-color . "White") (foreground-color . "Black") (vertical-scroll-bars) (internal-border-width . 0) (border-width . 0) (font . "-*-Menlo-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1") (fontsize . 0)) '(80 35 ((0 0 82 33)) ((nil " *empty*" 1 1 nil))))))

;; Global section:
(setq desktop-saved-frameset [frameset 1 (21804 6399 950232 0) (desktop . "206") "ianjones@Ians-MacBook-Pro.local" nil nil ((((font-backend mac-ct ns) (fontsize . 0) (font . "-*-Menlo-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1") (border-width . 0) (internal-border-width . 0) (vertical-scroll-bars) (foreground-color . "Black") (background-color . "White") (line-spacing) (left-fringe . 4) (right-fringe . 12) (menu-bar-lines . 0) (tool-bar-lines . 1) (title) (icon-type) (auto-raise) (auto-lower) (cursor-type . box) (scroll-bar-width . 0) (alpha) (fullscreen) (fringe) (display-type . color) (background-mode . light) (border-color . "#2a2a2a") (cursor-color . "Red") (visibility . t) (frameset--id . "1164-B818-4C8E-2AF5") (frameset--mini t . t) (height . 35) (width . 80) (modeline . t) (minibuffer . t) (unsplittable) (left . 100) (top . 100) (right-divider-width . 0) (bottom-divider-width . 0) (icon-name) (display . "Ians-MacBook-Pro.local") (explicit-name . t) (tool-bar-position . top)) ((min-height . 4) (min-width . 10) (min-height-ignore . 2) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 64) (min-pixel-width . 80) (min-pixel-height-ignore . 32) (min-pixel-width-ignore . 32) (min-pixel-height-safe . 16) (min-pixel-width-safe . 16)) leaf (pixel-width . 656) (pixel-height . 543) (total-width . 82) (total-height . 33) (normal-height . 1.0) (normal-width . 1.0) (buffer " *empty*" (selected . t) (hscroll . 0) (fringes 4 12 nil) (margins nil) (scroll-bars 0 0 t nil) (vscroll . 0) (dedicated) (point . 1) (start . 1))))])
(setq desktop-missing-file-warning nil)
(setq tags-file-name nil)
(setq tags-table-list nil)
(setq search-ring nil)
(setq regexp-search-ring nil)
(setq register-alist '((48 . "dfk")))
(setq file-name-history '("~/Library/Preferences/Aquamacs Emacs/Packages/ido.last" "/Users/ianjones/notes/interpersonal.org" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/magit-20150411.1731/magit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/git-commit-mode-20150330.1048/git-commit-mode-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/git-rebase-mode-20150122.1114/git-rebase-mode-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/tagedit-20141021.2139/tagedit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/s-20140910.334/s-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/rainbow-delimiters-20150320.17/rainbow-delimiters-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/projectile-20150405.126/projectile-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/smex-20141210.1422/smex-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/ido-ubiquitous-20150412.1842/ido-ubiquitous-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/ido-completing-read+-20150412.1842/ido-completing-read+-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/cider-20150412.827/cider-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/dash-20150311.2355/dash-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/pkg-info-20140610.630/pkg-info-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/epl-20150326.1212/epl-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/queue-0.1.1/queue-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/clojure-mode-extra-font-locking-20150110.505/clojure-mode-extra-font-locking-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/clojure-mode-20150410.2319/clojure-mode-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/paredit-20150217.713/paredit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/exec-path-from-shell-20141212.846/exec-path-from-shell-autoloads.el"))

;; Buffer section -- buffers listed in same order as in buffer list:
